/* Integration test: real GLB modules + real skinned character through the game loop (WebGL and KTX2 stubbed). */
import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const ctx2d=()=>new Proxy({},{get(t,k){if(k==='getImageData')return(x,y,w,h)=>({data:new Uint8ClampedArray(w*h*4).fill(128)});if(k==='createImageData')return(w,h)=>({data:new Uint8ClampedArray(w*h*4)});if(k==='createLinearGradient'||k==='createRadialGradient')return()=>({addColorStop(){}});if(k==='measureText')return()=>({width:10});return typeof t[k]!=='undefined'?t[k]:()=>{};},set(t,k,v){t[k]=v;return true;}});
const listeners=new Map();const els={};
function el(id){return {id,style:{},classList:{add(){},remove(){},toggle(){},contains(){return false;}},textContent:'',get innerHTML(){return this._ih||'';},set innerHTML(v){this._ih=v;if(v==='')this.children=[];},children:[],listeners:{},addEventListener(t,f){(this.listeners[t]=this.listeners[t]||[]).push(f);},querySelector(){return {textContent:''};},setPointerCapture(){},setAttribute(){},getAttribute(){return null;},removeAttribute(){},querySelectorAll(){return [];},getContext(){return ctx2d();},appendChild(c){this.children.push(c);},width:0,height:0};}
globalThis.document={querySelectorAll(){return [];},querySelector(){return null;},getElementById(id){return els[id]||(els[id]=el(id));},createElement(tag){if(tag==='canvas')return {width:0,height:0,getContext(){return ctx2d();}};return el('dyn');},createElementNS(){return {style:{},addEventListener(t,f){if(t==='error')setTimeout(()=>f(new Error('no images in node')),0);},removeEventListener(){},set src(v){}};},addEventListener(t,f){(listeners.get(t)||listeners.set(t,[]).get(t)).push(f);},body:{classList:{add(){}}},documentElement:{},hidden:false,pointerLockElement:null,exitPointerLock(){}};
globalThis.window=globalThis;globalThis.innerWidth=390;globalThis.innerHeight=844;globalThis.devicePixelRatio=2;globalThis.addEventListener=(t,f)=>{(listeners.get('w:'+t)||listeners.set('w:'+t,[]).get('w:'+t)).push(f);};
Object.defineProperty(globalThis,'navigator',{value:{maxTouchPoints:0,vibrate(){},hardwareConcurrency:4},configurable:true});
let stored=null;globalThis.localStorage={getItem(){return stored;},setItem(k,v){stored=v;}};
let rafCb=null;globalThis.requestAnimationFrame=f=>{rafCb=f;};globalThis.screen={};globalThis.self=globalThis;globalThis.ProgressEvent=class{constructor(t,i){this.type=t;Object.assign(this,i||{});}};
const THREE=await import('three');
const {GLTFLoader}=await import('three/examples/jsm/loaders/GLTFLoader.js');const {MeshoptDecoder}=await import('three/examples/jsm/libs/meshopt_decoder.module.js');
const root=path.resolve('public');const server=http.createServer((req,res)=>{fs.readFile(path.join(root,decodeURIComponent(req.url.split('?')[0])),(e,d)=>{if(e){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':'application/octet-stream'});res.end(d);});});await new Promise(r=>server.listen(8124,r));
class KtxStub extends THREE.Loader{load(u,ok){const t=new THREE.DataTexture(new Uint8Array([128,128,128,255]),1,1);t.needsUpdate=true;ok(t);}loadAsync(){return Promise.resolve(new THREE.DataTexture(new Uint8Array([128,128,128,255]),1,1));}}
const gltf=new GLTFLoader().setKTX2Loader(new KtxStub()).setMeshoptDecoder(MeshoptDecoder);const manifest=JSON.parse(fs.readFileSync('src/assets/manifest.json','utf8'));
const {MATERIAL_SPECS}=await import('../src/assets/AssetRegistry.js');
const cache=new Map();const cached=(k,fn)=>cache.has(k)?cache.get(k):(cache.set(k,fn().catch(e=>{console.log('LOAD FAIL',k,e.message);return null;})),cache.get(k));
const registry={manifest,available:{character:false},log:[],
  texture:async()=>{const t=new THREE.DataTexture(new Uint8Array([128,128,128,255]),1,1);t.needsUpdate=true;return t;},
  materialSet:async(id)=>manifest.materials[id]?{map:await registry.texture(),normalMap:await registry.texture(),roughnessMap:await registry.texture()}:null,
  environment:async()=>null,
  weapon:async(id)=>{const w=manifest.weapons&&manifest.weapons[id];if(!w)return null;return cached('wpn:'+id,async()=>{const g=await gltf.loadAsync('http://localhost:8124/'+w.path);const find=n=>g.scene.getObjectByName(n)||null;return {scene:g.scene,body:find('body'),mag:find('mag'),tip:find('tip'),eject:find('eject'),info:w};});},
  module:async(id)=>{const m=manifest.modules[id];if(!m)return null;return cached('mod:'+id,async()=>{const g=await gltf.loadAsync('http://localhost:8124/'+m.path);const meshes=[];g.scene.traverse(o=>{if(o.isMesh)meshes.push(o);});return {scene:g.scene,meshes,info:m};});},
  character:async()=>cached('char',async()=>{const c=manifest.characters.human_base;const [g0,g1,g2]=await Promise.all([gltf.loadAsync('http://localhost:8124/'+c.path),gltf.loadAsync('http://localhost:8124/'+c.lods.lod1),gltf.loadAsync('http://localhost:8124/'+c.lods.lod2)]);const skins={};for(const k in c.skins)skins[k]=await registry.texture();const kits={};for(const k in c.kits)kits[k]=await registry.texture();registry.available.character=true;return {gltf:g0,lod1:g1,lod2:g2,clips:g0.animations,skins,kits,info:c};}),
  pbr:async(name,opts={})=>{const spec=MATERIAL_SPECS[name]||{color:0x9a9a9a};return new THREE.MeshStandardMaterial({color:new THREE.Color(spec.color||0xffffff),vertexColors:!!opts.vertexColors,emissive:new THREE.Color(spec.emissive||0)});}};
const renderer={domElement:(els.gl=el('gl')),shadowMap:{enabled:false,type:0},info:{render:{calls:0,triangles:0},memory:{geometries:0,textures:0},programs:[],autoReset:true,reset(){}},toneMapping:0,toneMappingExposure:1,pr:1,setPixelRatio(p){this.pr=p;},getPixelRatio(){return this.pr;},setSize(){},render(scene,cam){scene.updateMatrixWorld();cam.updateMatrixWorld();let calls=0,tris=0;scene.traverse(o=>{if(o.visible&&(o.isMesh||o.isPoints||o.isSprite)){calls++;const g=o.geometry;if(g&&g.attributes.position){const n=g.index?g.index.count:g.attributes.position.count;tris+=(n/3)*(o.isInstancedMesh?o.count:1);}}});this.info.render.calls=calls;this.info.render.triangles=tris;},setRenderTarget(){},capabilities:{isWebGL2:true}};
const {startGameApp}=await import('../src/game/Game.js');
const t0=Date.now();const origLog=console.log;setTimeout(()=>{origLog('STALL? cache keys',[...cache.keys()].join(','),'els',Object.keys(els).length);},20000).unref();
await Promise.race([startGameApp({renderer,registry}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('startGameApp timeout')),40000))]).catch(e=>{console.log('START ERROR',e.message,e.stack&&e.stack.split('\n').slice(0,4).join(' | '));process.exit(1);});console.log('init ms',Date.now()-t0);
let t=1000;const frames=n=>{for(let i=0;i<n;i++){t+=16.7;rafCb(t);}};const key=(k,d)=>{for(const f of (listeners.get(d?'w:keydown':'w:keyup')||[]))f({key:k,preventDefault(){}});};
const R=window.__rdp,dbg=()=>R.dbg();frames(10);console.log('menu',JSON.stringify(dbg()));
{const sp=R.start();await new Promise(r=>setTimeout(r,40));for(let i=0;i<8;i++){(els.cardBtn.listeners.click||[]).forEach(f=>f());}await sp;}frames(120);console.log('play',JSON.stringify(dbg()),'roles',JSON.stringify(R.roles().slice(0,4)));
document.pointerLockElement=els.gl;const md=listeners.get('mousedown')||[],mu=listeners.get('mouseup')||[],mm=listeners.get('mousemove')||[];
key('w',true);frames(90);key('w',false);for(let r=0;r<12;r++){md.forEach(f=>f({button:0}));frames(12);mu.forEach(f=>f({button:0}));mm.forEach(f=>f({movementX:70,movementY:0}));frames(6);}
console.log('after firing',JSON.stringify(dbg()));
{ // animation liveness: sample bone rotations of live enemies over 40 frames
  const en=window.__rdp.enemiesRaw().filter(e=>e.state==='move'||e.state==='attack');
  for(const e of en.slice(0,3)){const m=e.model;const q0=m.bones.LeftUpLeg.quaternion.clone(),a0=m.bones.LeftArm.quaternion.clone();let legMax=0,armMax=0;for(let i=0;i<40;i++){frames(1);legMax=Math.max(legMax,q0.angleTo(m.bones.LeftUpLeg.quaternion));armMax=Math.max(armMax,a0.angleTo(m.bones.LeftArm.quaternion));}
    const acts=Object.entries(m.actions).filter(([n,a])=>a.isRunning()).map(([n,a])=>n+'(w'+a.getEffectiveWeight().toFixed(2)+(a.enabled?'':' DISABLED')+')');
    console.log('enemy',e.role,e.state,'gait',e.gait,'upper',e.upper,'| leg motion',legMax.toFixed(3),'arm motion',armMax.toFixed(3),'| running:',acts.join(' '));}
  // repeated hits (auto-fire) then let the reaction finish: does the upper body come back?
  const e=en[0];if(e){const m=e.model;for(let k=0;k<12;k++){m.fireUpper('hit');frames(2);}frames(60);const a0=m.bones.LeftArm.quaternion.clone();let armMax=0;for(let i=0;i<40;i++){frames(1);armMax=Math.max(armMax,a0.angleTo(m.bones.LeftArm.quaternion));}
    const acts=Object.entries(m.actions).filter(([n,a])=>a.isRunning()||a.enabled===false&&a.getEffectiveWeight()>0).map(([n,a])=>n+'(w'+a.getEffectiveWeight().toFixed(2)+(a.enabled?'':' DISABLED')+')');
    console.log('after 12 hits: upper',m.upper&&m.upper._clip.name,'enabled',m.upper&&m.upper.enabled,'weight',m.upper&&m.upper.getEffectiveWeight().toFixed(2),'oneshot',!!m.oneshot,'| arm motion',armMax.toFixed(3),'| running:',acts.join(' '));}
}
for(let i=0;i<40;i++){R.killAll();frames(90);(els.cardBtn.listeners.click||[]).forEach(f=>f());await new Promise(r=>setTimeout(r,5));(els.cardBtn.listeners.click||[]).forEach(f=>f());const d=dbg();if(d.mode==='loading'){await new Promise(r=>setTimeout(r,20));frames(10);}if(d.mode==='story'){for(let k=0;k<4;k++){(els.cardBtn.listeners.click||[]).forEach(f=>f());await new Promise(r=>setTimeout(r,30));}continue;}if(d.mode==='menu'){(els.mapPlay.listeners.click||[]).forEach(f=>f());await new Promise(r=>setTimeout(r,80));frames(10);continue;}if(d.mode==='over')break;}
await new Promise(r=>setTimeout(r,30));frames(30);const d=dbg();console.log('after grind',JSON.stringify(d));
let vis=0,inst=0;R.start;
server.close();console.log('FULL HARNESS OK');
